# Generated by Django 6.0.3 on 2026-03-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('stu_name', models.CharField(max_length=100)),
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'TProfileDetails',
                'verbose_name_plural': 'ProfileDetails',
            },
        ),
    ]
