# Generated by Django 6.0.3 on 2026-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_fname', models.CharField(max_length=50)),
                ('stu_age', models.IntegerField()),
                ('stu_dob', models.DateField()),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_web_link', models.URLField()),
                ('stu_profile_pic', models.ImageField(upload_to='images/')),
                ('stu_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stu_active', models.BooleanField(default=True)),
                ('cr_date', models.DateField(auto_now_add=True)),
                ('cr_time', models.TimeField(auto_now_add=True)),
                ('cr_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
